#!/bin/bash

THEME='grub-theme-numigi'

# Pre-authorise sudo
sudo echo
# Detect distro and set GRUB location and update method
GRUB_DIR='grub'
UPDATE_GRUB=''

if [ -e /etc/os-release ]; then

    source /etc/os-release

    if [[ "$ID" =~ (debian|ubuntu|solus) || \
          "$ID_LIKE" =~ (debian|ubuntu) ]]; then

        UPDATE_GRUB='update-grub'

        if [ -d /boot/efi/EFI/${ID} ]
        then
            GRUB_CFG_PATH="/boot/efi/EFI/${ID}/grub.cfg"
        fi

        # BLS etries have 'kernel' class, copy corresponding icon
        if [[ -d /boot/loader/entries && -e icons/${ID}.png ]]
        then
            cp icons/${ID}.png icons/kernel.png
        fi

        GRUB_DIR='grub2'
        UPDATE_GRUB="grub2-mkconfig -o ${GRUB_CFG_PATH}"
    fi
fi

sudo rm -r /boot/${GRUB_DIR}/themes/${THEME}

sudo mkdir -p /boot/${GRUB_DIR}/themes/${THEME}

sudo cp -r ${THEME}/* /boot/${GRUB_DIR}/themes/${THEME}

sudo sed -i '/^GRUB_THEME=/d' /etc/default/grub

sudo sed -i 's/^\(GRUB_TERMINAL\w*=.*\)/#\1/' /etc/default/grub

sudo sed -i -e :a -e '/^\n*$/{$d;N;};/\n$/ba' /etc/default/grub

# prompt -i "\nAdding new line to GRUB config"  # optional
# echo | sudo tee -a /etc/default/grub
echo "GRUB_THEME=\"/boot/${GRUB_DIR}/themes/${THEME}/theme.txt\"" | sudo tee -a /etc/default/grub